# Setup
title:               typo
tagline:             '| a scripting journey'
# description:         ''
url:                 https://typo.us.org
baseurl:             /
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate
