# Setup
title:               typo
tagline:             'A scripting journey'
# description:         ''
url:                 https://github.com/whoistypo/scripting.github.io
baseurl:             /
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate
