# Setup
title:               typo
tagline:             'a scripting journey'
# description:         ''
url:                 https://typo.us.org
baseurl:             /
paginate:            5
permalink:           pretty
pygments:            true

# Gems
plugins:
  - jekyll-paginate
