# Setup
title:               Nothing but typos
tagline:             'A scripting journey'
# description:         ''
url:                 http://typo.us.org
baseurl:             /
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Daniele Tozzi
  url:               https://typo.us.org
  email:             denymyservice@gmail.com

# Gems
plugins:
  - jekyll-paginate
